site_name: Extract Text
repo_url: https://github.com/rib-thiago/extract_text
repo_name: rib-thiago/extract_text
edit_uri: /tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/python.png
  favicon: assets/python.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css